pm_website/config/routes.rb
Rails.application.routes.draw do

  get 'packages/new'

  get 'sessions/new'

  root 'static_pages#home'

  get  '/openscadpm',    to: 'static_pages#OpenScadpm'

  get  '/documentation',    to: 'static_pages#Documentation'



  get  '/support',    to: 'static_pages#Support'

  get  '/mypackages',    to: 'static_pages#MyPackages'

  get  '/signup', to: 'users#new'

  get    '/login',   to: 'sessions#new'

  post   '/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'

  get '/newpackage', to: 'packages#new' 

  post '/newpackage', to: 'packages#create'

  resources :users

  resources :packages

end

pm_website/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pm_website/app/models/package.rb
class Package < ApplicationRecord
  before_save { self.link = link.downcase }
  validates :name, presence: true, length: { maximum: 50 },
                   uniqueness: { case_sensitive: false }
  validates :link, presence: true, length: { maximum: 200},
                   uniqueness: { case_sensitive: false }
  validates :package_info, presence: true, length: { minimum: 50 }

end

pm_website/app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 200 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :username, presence: true, length: { maximum: 40 }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true


  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

pm_website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

pm_website/app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :logged_in_user, only: [:edit]
  def index
    @packages = Package.paginate(page: params[:page])
  end

  def show
    @package = Package.find(params[:id])
  end

  def new
    @package = Package.new
  end

  def create
    @package = Package.new(package_params) 
    if @package.save
      flash[:success] = "Package was successfully added!"
      redirect_to @package
    else
      render 'new'
    end
  end

  def edit
    @package = Packages.find(params[:id])
  end

  private

    def package_params
      params.require(:package).permit(:name, :link, :package_info)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

pm_website/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid username or password'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

pm_website/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def OpenScadpm
  end

  def Documentation
  end

  def Support
  end

  def Packages
  end

  def MyPackages
  end

end

pm_website/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Thank you for joining the OpenSCAD community!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :username, :password,
                                   :password_confirmation)
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

pm_website/app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "OpenSCADpm"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

pm_website/app/helpers/packages_helper.rb
module PackagesHelper
end

pm_website/app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

pm_website/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

pm_website/app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

pm_website/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.openscad.org/">OpenSCAD Website</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "OpenSCADpm", openscadpm_path %></li>
      <li><%= link_to "Support", support_path %></li>
      <li><a href="http://www.openscad.org/documentation.html">Learn OpenSCAD</a></li>
    </ul>
  </nav>
</footer>

pm_website/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= image_tag("OpenSCAD-logo-2.png", :alt => "OpenSCAD logo", id: "logo1") %>
    <%= link_to "OpenSCAD", root_path, id: "logo2" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "OpenSCADpm",   openscadpm_path %></li>
        <li><%= link_to "Packages",   packages_path %></li>
        <li><%= link_to "Documentation",   documentation_path %></li>
        <li><%= link_to "Support",   support_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "My Packages", mypackages_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Package", newpackage_path %></li>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

pm_website/app/views/layouts/_search.html.erb
<div class="navbar">
  <div class="container">
    <%= form_tag(users_path, :method => "get", id: "search_form") do %>
      <table>
        <tr>
          <th>
            <%= text_field_tag :search, params[:search], placeholder: "Find Packages" %>
          </th>

          <th>
            <%= submit_tag "Search", :name => nil %>
          </th>
        </td>
      </table>
    <% end %>
  </div>
</div>

pm_website/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

pm_website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/search' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

      <%= yield %>      
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

pm_website/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

pm_website/app/views/static_pages/Documentation.html.erb
<% provide(:title, "Documentation") %>
<h1>Documentation</h1>
<p>Comprehensible OpenSCADpm Tutorials</p> 

pm_website/app/views/static_pages/MyPackages.html.erb
<% provide(:title, "My Packages") %>
<h1>My Packages</h1>
  <p>
  OpenSCADpm is a package manager for OpenSCAD. Find irresistible packages and use them for creating solid 3D CAD objects.
  </p>

pm_website/app/views/static_pages/OpenScadpm.html.erb
<% provide(:title, "About") %>
<h1>What is OpenSCADpm?</h1>
<p>OpenSCADpm helps developers share and re-use code in order to build wonderful designs.</p>

pm_website/app/views/static_pages/Packages.html.erb
<% provide(:title, "Packages") %>
<h1>OpenSCAD Packages</h1>
  <p>
  OpenSCADpm is a package manager for OpenSCAD. Find irresistible packages and use them for creating solid 3D CAD objects.
  </p>

pm_website/app/views/static_pages/Support.html.erb
<% provide(:title, "Support") %>
<h1>Contact Us</h1>
<p>
The number of packages for OpenSCAD is growing rapidly. Please let us know should you like to implement a missing feature.
</p>

pm_website/app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Build Splendid Models with OpenSCAD</h1>
  <h3>The Programmer's Solid 3D CAD Modeller</h3>
  <p>
  OpenSCADpm is a package manager for OpenSCAD. Find irresistible packages and use them for creating solid 3D CAD objects.
  </p>
  <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= image_tag("OpenSCAD-logo.png", :alt => "OpenSCAD logo") %>

pm_website/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>

	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label :email %>
	<%= f.email_field :email, class: 'form-control' %>

	<%= f.label :username %>
	<%= f.text_field :username, class: 'form-control' %>

	<%= f.label :password, "Password (Minimum 8 Characters)" %>
	<%= f.password_field :password, class: 'form-control' %>

	<%= f.label :password_confirmation, "Confirm Password" %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>

	<%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

pm_website/app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Are you sure?" } %>
  <% end %>

</li>

pm_website/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :password, "Password (Minimum 8 Characters)" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

    

pm_website/app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
  <<%= render @users %>
</ul>

<%= will_paginate %>

pm_website/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create Account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

pm_website/app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>, <%= @user.email %>, <%= @user.username %>
      </h1>
    </section>
  </aside>
</div>

pm_website/app/views/users/uploadpackage.html.erb
<% provide(:title, "Upload package") %>
<h1>Update a Package</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :link %>
      <%= f.text_field :link, class: 'form-control' %>

      <%= f.label :package_info %>
      <%= f.text_field :package_info, class: 'form-control' %>

      <%= f.submit "Upload Package", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>